[lint]
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-function"]

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true
optimizer = true
optimizer_runs = 2000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
